export const places =[
    {
        "id":1,
        "imgUrl":"https://cdn1.tripoto.com/media/filter/tst/img/2163002/Image/1642496887_image_cover.jpg",
        "package":"PACKAGE",
        "name":"Hike to a Natural Pool and Go Bushcrafting at this Luxury Camp | Moksham Himalayan Campsite, Pangot",
        "info":"",
    },
    {
        "id":2,
        "imgUrl":"https://cdn1.tripoto.com/media/filter/tst/img/2176903/Image/1657734830_image_cover_a.jpg",
        "name":"Explore One of Asia's Spookiest Spots While Unwinding Amidst Nature | Seegreen Lodges, Mussoorie",
        "package":"PACKAGE",
        "info":"",
    },
    {
        "id":3,
        "imgUrl":"https://cdn1.tripoto.com/media/filter/tst/img/2176903/Image/1654439464_revised_hsc.jpg",
        "name":"Hike to a Mountaintop & Swim in a Waterfall as You Experience Mukteshwar’s Magical Monsoon | Hisalu",
        "package":"PACKAGE",
        "info":"",
    },
    {
        "id":4,
        "imgUrl":"https://cdn1.tripoto.com/media/filter/tst/img/2176903/Image/1657204838_omya_img_cover_b.jpg",
        "name":"Take a Dip in a River and Ride on a Toy Train Amidst Mountains | Omya Forest Camps, Bir",
        "package":"PACKAGE",
        "info":"",
    },
    {
        "id":5,
        "imgUrl":"https://cdn1.tripoto.com/media/filter/tst/img/2176903/Image/1653394847_nw_c2.jpg",
        "name":"Trek to Triund and Stay At The Residence Of Kangra’s Maharaja | Clouds End Villa, Dharamshala",
        "package":"PACKAGE",
        "info":"",
    },
    {
        "id":6,
        "imgUrl":"https://cdn1.tripoto.com/media/filter/tst/img/2163002/Image/1640323403_image_cover_b.jpg",
        "name":"Explore an Artist’s Estate & Stay in a Kathkuni Home Hidden in Manali's Forests | NORTH",
        "package":"PACKAGE",
        "info":"",
    },
    {
        "id":7,
        "imgUrl":"https://cdn1.tripoto.com/media/filter/tst/img/2176903/Image/1654504108_ce_c1.jpg",
        "name":"Embark on an Adventure with Night Safari & Cycle Safari as You Spot Tigers | Mandaal Corbett",
        "package":"PACKAGE",
        "info":"",
        "location":"",
    },
    {
        "id":8,
        "imgUrl":"https://cdn1.tripoto.com/media/filter/tst/img/2176903/Image/1653391344_ln_c1.jpg",
        "name":"Embark on an Adventure with Night Safari & Cycle Safari as You Spot Tigers | Mandaal Corbett",
        "package":"PACKAGE",
        "info":"",
    },
]